Level2の実装完了：楽天APIの追加、flex massageの作成・表示
sgaku/intern-line-bot pull request #2
Opened 2023-03-27 09:22 UTC by sgaku

## 実装の背景・目的
実装の流れ
・楽天APIからのレスポンスを取得し、そこから本のタイトル、画像、評価、キャプション、urlを取得してflex massageとして表示しました

webhook_controller

7 initialize 
ランダムで表示するジャンルのリストを宣言しています。
リストの変数をどこに書けばいいか分からなかったので、起動時に初期化されるようにしました

18 fetchData API
楽天API周りの処理にRakutenWebServiceというパッケージを使いました。理由として、リクエストレスポンスが簡単にかけたのとカスタムで指定できるパラメータも書きやすかったからです。
.search(booksGenreId:@@gerne_list[rand(5)],sort:"reviewAverage")では、@@gerne_list[rand(5)]でジャンルのランダム化、sort:"reviewAverage"で高レート順にソートするようにしています。

66 flex
linebotのflex massageの構造部分です。apiから表示したいものを引数にし、jsonの対象箇所に入れるようにしています。

121 rate
flex massageの評価レートの部分です。jsonの文字列が長くなるためflex関数から分けて書いています。
review_average.to_iで評価値をintに変換し、５段階評価なので５回ループで回して星の色を判定しながら表示しています、星のurlはどこかで変数として持っていてもいいかもしれません。
## やったこと

- PR 内でやったことを箇条書きにしてください
・楽天APIの追加
・APIの結果を応答メッセージで表示
・flex massageの作成
・flex massageに画像、タイトル、評価レート、キャプション、購入ボタンを追加
・APIレスポンスで返すパラメータ（例えば本のタイトル）がnilの場合の対処を追加
## キャプチャ

https://user-images.githubusercontent.com/82754459/227893606-d5f8a5e4-ec44-4fa9-88d8-e93b4d9b0129.mov

## 補足

・実装重視でコードを書いてしまったので、汚いコードのままになっています。すいません。
・次はMVCを意識してかけるようになりたいです！

2023-03-27 10:42 UTC, yashi8484 requested changes
1日でよく実装できていると思います！早い！ 🚀 🚀 🚀 
`application_id` は秘匿情報に当たるかと思いますので、生の値が見えないようにしましょう〜 🙅

2023-03-27 10:42 UTC, yashi8484 commented on .gitignore
> +config/environments/*.local.yml
[nits] `config/**/*.local.yml` でまとめられそう。

2023-03-27 10:42 UTC, yashi8484 commented on Gemfile
> +gem 'activesupport', '~> 4.2', '>= 4.2.11'
[IMO] Rails の中に activesupport は同梱されているため、別途インストールしなくても良いと思います 🤔

2023-03-27 10:42 UTC, yashi8484 commented on app/controllers/webhook_controller.rb
> +    @@gerne_list = ["001004001","001004002","001004008","001004004","001004016"];
[IMO] gerne_list の値は変化なく常に固定で良いはず...なので、定数にしたほうが良さそう！
ref: https://docs.ruby-lang.org/ja/latest/doc/spec=2fvariables.html#const

2023-03-27 10:42 UTC, yashi8484 commented on app/controllers/webhook_controller.rb
> +    response = RakutenWebService::Books::Book.search(booksGenreId:@@gerne_list[rand(5)],sort:"reviewAverage")
よく書けています！
ですが、実は Ruby には「配列の中からランダムで要素を取得する」関数が用意されているため、もっと楽に書けます〜 📝 
ref: https://docs.ruby-lang.org/ja/latest/method/Array/i/sample.html

2023-03-27 10:42 UTC, yashi8484 commented on app/controllers/webhook_controller.rb
> +    response = RakutenWebService::Books::Book.search(booksGenreId:@@gerne_list[rand(5)],sort:"reviewAverage")
[ask] 今回、Rakuten Books Total Search API を使っているのかな？
[IMO] もしそうであれば、 Input Parameters に件数を指定できるパラメータがありそうなので、`books.first()` で絞らなくても、最初から「最大10件まで取得する」ことができそう。
https://webservice.rakuten.co.jp/documentation/books-total-search

2023-03-27 10:42 UTC, yashi8484 commented on app/controllers/webhook_controller.rb
> +    return show_items[rand(10)]
[ask] ここで `rand(10)` としているのはどういう意図からでしょう？

2023-03-27 10:42 UTC, yashi8484 commented on app/controllers/webhook_controller.rb
> +        "https://scdn.line-apps.com/n/channel_devcenter/img/fx/review_gold_star_28.png"
[nits][IMO] せっかく config gem を入れているので、星画像の URL は `settings.yml` に持っても良さそう。

2023-03-27 10:42 UTC, yashi8484 commented on config/initializers/raketen.rb
> +    c.application_id = 1060444232620337157
[IMO] この `application_id` が露出すると誰でも自由に Rakuten API を叩けてしまうため、 LINE の secret と同様に環境変数として定義したほうが良いですねー 👀

2023-03-27 11:13 UTC, ferretdayo reviewed
RakutenのAPIを叩いて、FlexMessageを表示するところまで早くできていて素晴らしいですー！

2023-03-27 11:13 UTC, ferretdayo commented on app/controllers/webhook_controller.rb
> +    response = RakutenWebService::Books::Book.search(booksGenreId:@@gerne_list[rand(5)],sort:"reviewAverage")
[IMO]ジャンルの数が変わると`rand(5)`の5を変更することになります。
ランダムの値を取得する関数の引数に、ジャンルの数(`配列の変数.size`)を活用すると、ジャンルを変更した時に変更箇所が減って、より良いかもです！

ex) `rand(@@gerne_list[rand(@@gerne_list.size)])`

2023-03-27 11:13 UTC, ferretdayo commented on config/settings.yml
> + level1_book_url : https://books.rakuten.co.jp/rb/16367537/
[nits]もし`level1_book_url`を使わないのであれば、削除しても良いと思いますー👀

2023-03-27 11:13 UTC, ferretdayo commented on app/controllers/webhook_controller.rb
> +  def flex(title,image,url,review_average,item_caption)
処理で分けて記述しているのいいと思います！

[nits]何をする関数なのかもう少し分かる関数名だとより良いかもです！
ex: `build_flex_message`等

2023-03-28 02:43 UTC, yashi8484 approved these changes
最低限直しておいたほうが良いところは直っており、大筋良さそうなので approve します！
残りのコメントへの対応や、MVC を意識したコードの書き方等についてもぜひチャレンジしてみてください〜 🚀 
![pokemon_water](https://user-images.githubusercontent.com/30618030/228113737-18c5e362-f210-4fdc-8b59-56e5af5597d9.png)

2023-03-28 02:43 UTC, yashi8484 commented on app/controllers/webhook_controller.rb
> +require 'active_support/all'
[nits] この require も不要そう？

2023-03-28 02:43 UTC, yashi8484 commented on config/initializers/raketen.rb
> +    c.application_id = ENV["RAKUTEN_APP_ID"]
💯

2023-03-28 02:43 UTC, yashi8484 commented on config/settings.yml
> + gray_star : https://scdn.line-apps.com/n/channel_devcenter/img/fx/review_gray_star_28.png
👍

2023-03-28 04:49 UTC, ferretdayo commented
ありがとうございます。
大丈夫だと思います！

2023-03-28 06:57 UTC, merged